import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

export const metadata: Metadata = {
  title: "Life is a Game",
  description: "Generated by create next app",
};

const blender = localFont({
  src: "../public/assets/fonts/Blender-Pro-Bold.ttf",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={blender.className}>{children}</body>
    </html>
  );
}
