import type { Metadata } from "next";

import { Orbitron, Play } from "next/font/google";

import "./globals.css";

export const metadata: Metadata = {
  title: "Life is a Game",
  description: "Generated by create next app",
};

const play = Play({ subsets: ["latin"], weight: ["400", "700"] });

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/assets/images/favicon.png" sizes="32x32" />
      </head>
      <body className={`bg-black ${play.className}`}>{children}</body>
    </html>
  );
}
