import type { Metadata } from "next";

import { Play } from "next/font/google";

import "./globals.css";
import ReduxProvider from "../redux/ReduxProvider";

export const metadata: Metadata = {
  title: "Life is a Game",
  description: "Generated by create next app",
};

const play = Play({ subsets: ["latin"], weight: ["400", "700"] });

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`bg-black ${play.className}`}>
        <ReduxProvider>{children}</ReduxProvider>
      </body>
    </html>
  );
}
